name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator:

flutter:
  uses-material-design: true
