name: flutter_reactive_ble
description: Reactive Bluetooth low energy (BLE) plugin that can communicate with multiple devices
version: 0.1.0
author: Philips Hue
homepage:

environment:
  sdk: ^2.3.0-dev

dependencies:
  flutter:
    sdk: flutter
  functional_data: ^0.2.3
  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mockito: ^4.1.1
  dependency_validator: ^1.4.2
  functional_data_generator: ^0.2.3
  flutter_reactive_ble_example:
    path: example

flutter:
  plugin:
    androidPackage: com.signify.hue.flutterreactiveble
    pluginClass: ReactiveBlePlugin
